#!/usr/bin/env python3
"""Analyze TOPAS dose CSV outputs against beamline Whitmore metrics."""

from __future__ import annotations

import argparse
import json
import math
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
try:
    from scipy.optimize import curve_fit
except Exception:  # pragma: no cover - fallback if scipy is unavailable
    curve_fit = None


AXIS_HEADER_RE = re.compile(
    r"^#\s*([XYZ])\s+in\s+(\d+)\s+bins\s+of\s+([0-9eE+\-.]+)\s+cm\s*$",
    re.IGNORECASE,
)
REPORT_HEADER_RE = re.compile(
    r"^#\s*(.+?)\s*\(\s*([^)]+?)\s*\)\s*:\s*(.+?)\s*$",
    re.IGNORECASE,
)


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Extract key focused beamline metrics from TOPAS CSV dose grids."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=root / "runs" / "manifest.json",
        help="Manifest generated by build_asymmetric_sweep.py",
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=root / "config" / "benchmark_reference.json",
        help="Whitmore JSON with Table 2 and Supplementary Table 3 values.",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=root / "runs" / "analysis",
        help="Directory for analysis artifacts.",
    )
    parser.add_argument(
        "--csv",
        nargs="*",
        type=Path,
        default=[],
        help="Optional direct CSV analysis mode (without a manifest).",
    )
    parser.add_argument(
        "--energy",
        type=int,
        default=0,
        help="Energy in MeV for direct --csv mode (to compare to Whitmore).",
    )
    parser.add_argument(
        "--g4",
        type=float,
        default=float("nan"),
        help="Q4 gradient in T/m for direct --csv mode (optional).",
    )
    parser.add_argument("--tol-z-cm", type=float, default=0.5, help="Tolerance for z_hat (cm).")
    parser.add_argument(
        "--tol-sigma-x-cm", type=float, default=0.2, help="Tolerance for sigma_x (cm)."
    )
    parser.add_argument(
        "--tol-sigma-y-cm", type=float, default=0.2, help="Tolerance for sigma_y (cm)."
    )
    parser.add_argument(
        "--tol-entrance-pct",
        type=float,
        default=5.0,
        help="Tolerance for entrance dose (%%) relative to Whitmore.",
    )
    parser.add_argument(
        "--entrance-mode",
        choices=["on_axis", "plane_max", "integrated_xy"],
        default="on_axis",
        help=(
            "Which entrance metric to use for pass/fail and weighted error: "
            "on_axis (center voxel z=0 normalized by centerline peak), "
            "plane_max (max voxel in entrance plane normalized by global peak), "
            "integrated_xy (entrance depth-dose integrated over x,y normalized by integrated peak)."
        ),
    )
    parser.add_argument(
        "--z-mode",
        choices=["integrated_xy", "on_axis", "global_max"],
        default="integrated_xy",
        help=(
            "Which z-hat definition to use for scoring: "
            "integrated_xy (argmax of depth-dose integrated over x,y), "
            "on_axis (centerline peak depth), or global_max (global 3D peak depth)."
        ),
    )
    parser.add_argument(
        "--sigma-mode",
        choices=["integrated_xy", "on_axis", "global_max", "independent_xy_min"],
        default="integrated_xy",
        help=(
            "Which sigma definition to use for scoring: "
            "integrated_xy (spot size at integrated-depth peak), "
            "on_axis (spot size at on-axis z-hat), "
            "global_max (spot size at global-peak z-hat), or "
            "independent_xy_min (sigma_x and sigma_y each taken at its own depth-wise minimum)."
        ),
    )
    parser.add_argument(
        "--sigma-fit-mode",
        choices=["profile_1d", "gaussian_2d", "paper_strict"],
        default="profile_1d",
        help=(
            "How sigma_x/sigma_y are extracted from each z slice: "
            "profile_1d fits 1D lines through slice peak (legacy), "
            "gaussian_2d fits an axis-aligned 2D Gaussian over the full slice, "
            "paper_strict enforces paper-style centerline profile Gaussian fits at on-axis focal depth."
        ),
    )
    parser.add_argument(
        "--paper-strict",
        action="store_true",
        help=(
            "Force paper-style extraction/scoring settings: z_mode=on_axis, "
            "sigma_mode=on_axis, entrance_mode=on_axis, sigma_fit_mode=paper_strict."
        ),
    )
    parser.add_argument(
        "--io-retries",
        type=int,
        default=5,
        help="Retry count for CSV/header reads on transient filesystem timeouts.",
    )
    parser.add_argument(
        "--io-retry-delay-sec",
        type=float,
        default=0.5,
        help="Delay in seconds between I/O retries.",
    )
    args = parser.parse_args()
    if args.paper_strict:
        args.z_mode = "on_axis"
        args.sigma_mode = "on_axis"
        args.entrance_mode = "on_axis"
        args.sigma_fit_mode = "paper_strict"
    return args


def load_reference(path: Path) -> Dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def parse_topas_header(csv_path: Path, retries: int = 1, retry_delay_sec: float = 0.0) -> Dict[str, float]:
    attempts = max(1, int(retries))
    for attempt in range(1, attempts + 1):
        try:
            header = {}
            with csv_path.open("r", encoding="utf-8") as f:
                for line in f:
                    if not line.startswith("#"):
                        break
                    match = AXIS_HEADER_RE.match(line.strip())
                    if match:
                        axis = match.group(1).upper()
                        header[f"n{axis.lower()}"] = int(match.group(2))
                        header[f"d{axis.lower()}_cm"] = float(match.group(3))
                        continue
                    report_match = REPORT_HEADER_RE.match(line.strip())
                    if report_match:
                        quantity = report_match.group(1).strip()
                        unit = report_match.group(2).strip()
                        reports = [value.strip() for value in report_match.group(3).split() if value.strip()]
                        if reports:
                            header["quantity_name"] = quantity
                            header["quantity_unit"] = unit
                            header["report_names"] = reports
            return header
        except (OSError, TimeoutError):
            if attempt >= attempts:
                raise
            time.sleep(max(0.0, retry_delay_sec))
    return {}


def load_topas_grid(
    csv_path: Path,
    retries: int = 1,
    retry_delay_sec: float = 0.0,
) -> Tuple[np.ndarray, Dict[str, float]]:
    header = parse_topas_header(csv_path, retries=retries, retry_delay_sec=retry_delay_sec)

    attempts = max(1, int(retries))
    raw = None
    for attempt in range(1, attempts + 1):
        try:
            raw = np.loadtxt(str(csv_path), comments="#", delimiter=",")
            break
        except (OSError, TimeoutError):
            if attempt >= attempts:
                raise
            time.sleep(max(0.0, retry_delay_sec))

    if raw is None:
        raise ValueError(f"Could not read data rows from {csv_path}")
    if raw.size == 0:
        raise ValueError(f"No data rows in {csv_path}")
    if raw.ndim == 1:
        raw = raw.reshape(1, -1)
    if raw.shape[1] < 4:
        raise ValueError(f"Expected at least 4 columns (ix,iy,iz,dose) in {csv_path}")

    ix = raw[:, 0].astype(int)
    iy = raw[:, 1].astype(int)
    iz = raw[:, 2].astype(int)
    dose = raw[:, 3].astype(float)

    nx = int(header.get("nx", int(ix.max()) + 1))
    ny = int(header.get("ny", int(iy.max()) + 1))
    nz = int(header.get("nz", int(iz.max()) + 1))
    grid = np.zeros((nx, ny, nz), dtype=np.float64)
    grid[ix, iy, iz] = dose

    if "dx_cm" not in header or "dy_cm" not in header or "dz_cm" not in header:
        raise ValueError(f"Could not read voxel spacing from TOPAS header in {csv_path}")

    return grid, header


def load_topas_report_grids(
    csv_path: Path,
    retries: int = 1,
    retry_delay_sec: float = 0.0,
) -> Tuple[Dict[str, np.ndarray], Dict[str, float]]:
    """Load a TOPAS CSV with one or more scorer report columns.

    The first three columns are assumed to be voxel indices `(ix, iy, iz)`.
    Every remaining column is treated as one report field, for example
    `Sum`, `Mean`, or `Standard_Deviation`.
    """

    header = parse_topas_header(csv_path, retries=retries, retry_delay_sec=retry_delay_sec)

    attempts = max(1, int(retries))
    raw = None
    for attempt in range(1, attempts + 1):
        try:
            raw = np.loadtxt(str(csv_path), comments="#", delimiter=",")
            break
        except (OSError, TimeoutError):
            if attempt >= attempts:
                raise
            time.sleep(max(0.0, retry_delay_sec))

    if raw is None:
        raise ValueError(f"Could not read data rows from {csv_path}")
    if raw.size == 0:
        raise ValueError(f"No data rows in {csv_path}")
    if raw.ndim == 1:
        raw = raw.reshape(1, -1)
    if raw.shape[1] < 4:
        raise ValueError(f"Expected at least 4 columns (ix,iy,iz,report...) in {csv_path}")

    ix = raw[:, 0].astype(int)
    iy = raw[:, 1].astype(int)
    iz = raw[:, 2].astype(int)
    report_data = raw[:, 3:].astype(float)

    nx = int(header.get("nx", int(ix.max()) + 1))
    ny = int(header.get("ny", int(iy.max()) + 1))
    nz = int(header.get("nz", int(iz.max()) + 1))

    report_names = list(header.get("report_names", []))
    if len(report_names) != report_data.shape[1]:
        report_names = [f"report_{idx}" for idx in range(report_data.shape[1])]

    report_grids: Dict[str, np.ndarray] = {}
    for idx, report_name in enumerate(report_names):
        grid = np.zeros((nx, ny, nz), dtype=np.float64)
        grid[ix, iy, iz] = report_data[:, idx]
        report_grids[str(report_name)] = grid

    if "dx_cm" not in header or "dy_cm" not in header or "dz_cm" not in header:
        raise ValueError(f"Could not read voxel spacing from TOPAS header in {csv_path}")

    return report_grids, header


def weighted_sigma(coords_cm: np.ndarray, profile: np.ndarray) -> float:
    values = np.asarray(profile, dtype=float)
    if np.all(values <= 0.0):
        return float("nan")
    # Remove a flat baseline to reduce broadening from low-dose tails.
    values = np.clip(values - np.min(values), 0.0, None)
    if np.all(values == 0.0):
        values = np.clip(profile, 0.0, None)
    norm = np.sum(values)
    if norm <= 0:
        return float("nan")
    mu = float(np.sum(coords_cm * values) / norm)
    var = float(np.sum(values * (coords_cm - mu) ** 2) / norm)
    return math.sqrt(max(var, 0.0))


def gaussian_with_offset(x: np.ndarray, amp: float, mu: float, sigma: float, offset: float) -> np.ndarray:
    return offset + amp * np.exp(-0.5 * ((x - mu) / sigma) ** 2)


def gaussian2d_with_offset(
    coords: Tuple[np.ndarray, np.ndarray],
    amp: float,
    mu_x: float,
    mu_y: float,
    sigma_x: float,
    sigma_y: float,
    offset: float,
) -> np.ndarray:
    x, y = coords
    return offset + amp * np.exp(
        -0.5 * (((x - mu_x) / sigma_x) ** 2 + ((y - mu_y) / sigma_y) ** 2)
    )


def weighted_sigma_2d(
    x_coords_cm: np.ndarray,
    y_coords_cm: np.ndarray,
    dose_2d: np.ndarray,
) -> Tuple[float, float]:
    values = np.asarray(dose_2d, dtype=float)
    if values.size == 0 or np.all(values <= 0.0):
        return float("nan"), float("nan")
    values = np.clip(values - np.min(values), 0.0, None)
    if np.all(values == 0.0):
        values = np.clip(dose_2d, 0.0, None)
    norm = float(np.sum(values))
    if norm <= 0.0:
        return float("nan"), float("nan")

    xx, yy = np.meshgrid(x_coords_cm, y_coords_cm, indexing="ij")
    mu_x = float(np.sum(xx * values) / norm)
    mu_y = float(np.sum(yy * values) / norm)
    var_x = float(np.sum(values * (xx - mu_x) ** 2) / norm)
    var_y = float(np.sum(values * (yy - mu_y) ** 2) / norm)
    return math.sqrt(max(var_x, 0.0)), math.sqrt(max(var_y, 0.0))


def fitted_sigma_2d(
    x_coords_cm: np.ndarray,
    y_coords_cm: np.ndarray,
    dose_2d: np.ndarray,
) -> Tuple[float, float]:
    weighted_sx, weighted_sy = weighted_sigma_2d(x_coords_cm, y_coords_cm, dose_2d)
    if curve_fit is None:
        return weighted_sx, weighted_sy

    values = np.clip(np.asarray(dose_2d, dtype=float), 0.0, None)
    peak = float(np.max(values))
    if peak <= 0.0:
        return float("nan"), float("nan")

    xx, yy = np.meshgrid(x_coords_cm, y_coords_cm, indexing="ij")
    min_val = float(np.min(values))
    mask = values >= 0.10 * peak
    if int(np.count_nonzero(mask)) < 16:
        return weighted_sx, weighted_sy

    x_fit = xx[mask].ravel()
    y_fit = yy[mask].ravel()
    z_fit = values[mask].ravel()

    peak_index = int(np.argmax(values))
    peak_ix, peak_iy = np.unravel_index(peak_index, values.shape)
    sigma_x0 = weighted_sx if np.isfinite(weighted_sx) and weighted_sx > 0 else max(np.diff(x_coords_cm).mean(), 1e-3)
    sigma_y0 = weighted_sy if np.isfinite(weighted_sy) and weighted_sy > 0 else max(np.diff(y_coords_cm).mean(), 1e-3)
    p0 = [
        max(peak - min_val, 1e-12),
        float(x_coords_cm[peak_ix]),
        float(y_coords_cm[peak_iy]),
        float(sigma_x0),
        float(sigma_y0),
        max(min_val, 0.0),
    ]
    lower = [
        0.0,
        float(np.min(x_coords_cm)) - 1.0,
        float(np.min(y_coords_cm)) - 1.0,
        1e-6,
        1e-6,
        0.0,
    ]
    upper = [
        np.inf,
        float(np.max(x_coords_cm)) + 1.0,
        float(np.max(y_coords_cm)) + 1.0,
        100.0,
        100.0,
        np.inf,
    ]

    try:
        popt, _ = curve_fit(
            gaussian2d_with_offset,
            (x_fit, y_fit),
            z_fit,
            p0=p0,
            bounds=(lower, upper),
            maxfev=50000,
        )
        return abs(float(popt[3])), abs(float(popt[4]))
    except Exception:
        return weighted_sx, weighted_sy


def fitted_sigma(coords_cm: np.ndarray, profile: np.ndarray) -> float:
    weighted = weighted_sigma(coords_cm, profile)
    if curve_fit is None:
        return weighted

    values = np.clip(np.asarray(profile, dtype=float), 0.0, None)
    peak = float(np.max(values))
    if peak <= 0:
        return float("nan")

    # Fit only near the main lobe to reduce broad low-dose tails.
    mask = values >= 0.10 * peak
    x_fit = coords_cm[mask]
    y_fit = values[mask]
    if x_fit.size < 5:
        return weighted

    sigma0 = weighted if np.isfinite(weighted) and weighted > 0 else max(np.diff(coords_cm).mean(), 1e-3)
    p0 = [peak, float(x_fit[np.argmax(y_fit)]), float(sigma0), float(np.min(y_fit))]
    lower = [0.0, float(np.min(coords_cm)) - 1.0, 1e-6, 0.0]
    upper = [np.inf, float(np.max(coords_cm)) + 1.0, 100.0, np.inf]

    try:
        popt, _ = curve_fit(
            gaussian_with_offset,
            x_fit,
            y_fit,
            p0=p0,
            bounds=(lower, upper),
            maxfev=20000,
        )
        return abs(float(popt[2]))
    except Exception:
        return weighted


def fitted_sigma_full_profile(coords_cm: np.ndarray, profile: np.ndarray) -> float:
    """Fit Gaussian+offset over the full 1D profile (paper-strict helper)."""
    weighted = weighted_sigma(coords_cm, profile)
    if curve_fit is None:
        return weighted

    values = np.clip(np.asarray(profile, dtype=float), 0.0, None)
    peak = float(np.max(values))
    if peak <= 0:
        return float("nan")

    sigma0 = (
        weighted
        if np.isfinite(weighted) and weighted > 0
        else max(np.diff(coords_cm).mean(), 1e-3)
    )
    p0 = [peak, float(coords_cm[np.argmax(values)]), float(sigma0), float(np.min(values))]
    lower = [0.0, float(np.min(coords_cm)) - 1.0, 1e-6, 0.0]
    upper = [np.inf, float(np.max(coords_cm)) + 1.0, 100.0, np.inf]

    try:
        popt, _ = curve_fit(
            gaussian_with_offset,
            coords_cm,
            values,
            p0=p0,
            bounds=(lower, upper),
            maxfev=30000,
        )
        return abs(float(popt[2]))
    except Exception:
        return weighted


def extract_metrics_from_grid(
    grid: np.ndarray,
    dx_cm: float,
    dy_cm: float,
    dz_cm: float,
    sigma_fit_mode: str = "profile_1d",
) -> Dict[str, float]:
    nx, ny, nz = grid.shape
    cx = nx // 2
    cy = ny // 2

    on_axis = grid[cx, cy, :]
    peak_index_on_axis = int(np.argmax(on_axis))
    peak_on_axis = float(on_axis[peak_index_on_axis])
    depth_integrated = np.sum(grid, axis=(0, 1))
    peak_index_integrated = int(np.argmax(depth_integrated))
    peak_integrated = float(depth_integrated[peak_index_integrated])
    global_peak = float(np.max(grid))
    peak_index_global = int(np.argmax(grid))
    peak_index_global_x, peak_index_global_y, peak_index_global_z = np.unravel_index(
        peak_index_global, grid.shape
    )
    z_hat_on_axis_cm = (peak_index_on_axis + 0.5) * dz_cm
    z_hat_integrated_cm = (peak_index_integrated + 0.5) * dz_cm
    z_hat_global_cm = (peak_index_global_z + 0.5) * dz_cm

    x_coords = (np.arange(nx, dtype=float) + 0.5 - nx / 2.0) * dx_cm
    y_coords = (np.arange(ny, dtype=float) + 0.5 - ny / 2.0) * dy_cm

    focal_slice_integrated = grid[:, :, peak_index_integrated]
    ix_peak_integrated, iy_peak_integrated = np.unravel_index(
        int(np.argmax(focal_slice_integrated)), focal_slice_integrated.shape
    )
    x_profile_integrated = grid[:, iy_peak_integrated, peak_index_integrated]
    y_profile_integrated = grid[ix_peak_integrated, :, peak_index_integrated]
    sigma_x_weighted_integrated_cm = weighted_sigma(x_coords, x_profile_integrated)
    sigma_y_weighted_integrated_cm = weighted_sigma(y_coords, y_profile_integrated)
    sigma_x_integrated_profile_cm = fitted_sigma(x_coords, x_profile_integrated)
    sigma_y_integrated_profile_cm = fitted_sigma(y_coords, y_profile_integrated)
    sigma_x_integrated_2d_cm, sigma_y_integrated_2d_cm = fitted_sigma_2d(
        x_coords, y_coords, focal_slice_integrated
    )

    focal_slice = grid[:, :, peak_index_on_axis]
    ix_peak, iy_peak = np.unravel_index(int(np.argmax(focal_slice)), focal_slice.shape)

    # Use profiles through the focal-slice peak location, not only geometric center.
    x_profile = grid[:, iy_peak, peak_index_on_axis]
    y_profile = grid[ix_peak, :, peak_index_on_axis]
    # Paper-style centerline profiles through the geometric center voxel.
    x_profile_center = grid[:, cy, peak_index_on_axis]
    y_profile_center = grid[cx, :, peak_index_on_axis]
    sigma_x_weighted_cm = weighted_sigma(x_coords, x_profile)
    sigma_y_weighted_cm = weighted_sigma(y_coords, y_profile)
    sigma_x_on_axis_profile_cm = fitted_sigma(x_coords, x_profile)
    sigma_y_on_axis_profile_cm = fitted_sigma(y_coords, y_profile)
    sigma_x_on_axis_center_profile_cm = fitted_sigma_full_profile(x_coords, x_profile_center)
    sigma_y_on_axis_center_profile_cm = fitted_sigma_full_profile(y_coords, y_profile_center)
    sigma_x_on_axis_2d_cm, sigma_y_on_axis_2d_cm = fitted_sigma_2d(
        x_coords, y_coords, focal_slice
    )

    focal_slice_global = grid[:, :, peak_index_global_z]
    ix_peak_global_slice, iy_peak_global_slice = np.unravel_index(
        int(np.argmax(focal_slice_global)), focal_slice_global.shape
    )
    x_profile_global = grid[:, iy_peak_global_slice, peak_index_global_z]
    y_profile_global = grid[ix_peak_global_slice, :, peak_index_global_z]
    sigma_x_weighted_global_cm = weighted_sigma(x_coords, x_profile_global)
    sigma_y_weighted_global_cm = weighted_sigma(y_coords, y_profile_global)
    sigma_x_global_profile_cm = fitted_sigma(x_coords, x_profile_global)
    sigma_y_global_profile_cm = fitted_sigma(y_coords, y_profile_global)
    sigma_x_global_2d_cm, sigma_y_global_2d_cm = fitted_sigma_2d(
        x_coords, y_coords, focal_slice_global
    )

    sigma_x_entrance_2d_cm, sigma_y_entrance_2d_cm = fitted_sigma_2d(
        x_coords, y_coords, grid[:, :, 0]
    )

    # Depth-wise sigma traces so x/y can optionally be selected at independent depths.
    sigma_x_trace_profile = np.full(nz, np.nan, dtype=float)
    sigma_y_trace_profile = np.full(nz, np.nan, dtype=float)
    sigma_x_trace_2d = np.full(nz, np.nan, dtype=float)
    sigma_y_trace_2d = np.full(nz, np.nan, dtype=float)
    sigma_x_trace_center_profile = np.full(nz, np.nan, dtype=float)
    sigma_y_trace_center_profile = np.full(nz, np.nan, dtype=float)
    for iz in range(nz):
        sl = grid[:, :, iz]
        ix_peak_z, iy_peak_z = np.unravel_index(int(np.argmax(sl)), sl.shape)
        x_profile_z = grid[:, iy_peak_z, iz]
        y_profile_z = grid[ix_peak_z, :, iz]
        sigma_x_trace_profile[iz] = fitted_sigma(x_coords, x_profile_z)
        sigma_y_trace_profile[iz] = fitted_sigma(y_coords, y_profile_z)
        sigma_x_trace_center_profile[iz] = fitted_sigma_full_profile(
            x_coords, grid[:, cy, iz]
        )
        sigma_y_trace_center_profile[iz] = fitted_sigma_full_profile(
            y_coords, grid[cx, :, iz]
        )
        sx2d_z, sy2d_z = fitted_sigma_2d(x_coords, y_coords, sl)
        sigma_x_trace_2d[iz] = sx2d_z
        sigma_y_trace_2d[iz] = sy2d_z

    if sigma_fit_mode == "gaussian_2d":
        sigma_x_integrated_cm = sigma_x_integrated_2d_cm
        sigma_y_integrated_cm = sigma_y_integrated_2d_cm
        sigma_x_on_axis_cm = sigma_x_on_axis_2d_cm
        sigma_y_on_axis_cm = sigma_y_on_axis_2d_cm
        sigma_x_global_cm = sigma_x_global_2d_cm
        sigma_y_global_cm = sigma_y_global_2d_cm
        sigma_x_trace = sigma_x_trace_2d
        sigma_y_trace = sigma_y_trace_2d
    elif sigma_fit_mode == "paper_strict":
        # Paper-style extraction: on-axis peak depth + Gaussian fits on centerline x/y profiles.
        sigma_x_integrated_cm = sigma_x_on_axis_center_profile_cm
        sigma_y_integrated_cm = sigma_y_on_axis_center_profile_cm
        sigma_x_on_axis_cm = sigma_x_on_axis_center_profile_cm
        sigma_y_on_axis_cm = sigma_y_on_axis_center_profile_cm
        sigma_x_global_cm = sigma_x_on_axis_center_profile_cm
        sigma_y_global_cm = sigma_y_on_axis_center_profile_cm
        sigma_x_trace = sigma_x_trace_center_profile
        sigma_y_trace = sigma_y_trace_center_profile
    else:
        sigma_x_integrated_cm = sigma_x_integrated_profile_cm
        sigma_y_integrated_cm = sigma_y_integrated_profile_cm
        sigma_x_on_axis_cm = sigma_x_on_axis_profile_cm
        sigma_y_on_axis_cm = sigma_y_on_axis_profile_cm
        sigma_x_global_cm = sigma_x_global_profile_cm
        sigma_y_global_cm = sigma_y_global_profile_cm
        sigma_x_trace = sigma_x_trace_profile
        sigma_y_trace = sigma_y_trace_profile

    def min_sigma_index_and_value(trace: np.ndarray) -> Tuple[int, float]:
        valid = np.isfinite(trace) & (trace > 0.0)
        if not np.any(valid):
            return -1, float("nan")
        valid_indices = np.where(valid)[0]
        local = int(np.argmin(trace[valid]))
        idx = int(valid_indices[local])
        return idx, float(trace[idx])

    sigma_x_min_idx, sigma_x_independent_min_cm = min_sigma_index_and_value(sigma_x_trace)
    sigma_y_min_idx, sigma_y_independent_min_cm = min_sigma_index_and_value(sigma_y_trace)
    z_hat_sigma_x_min_cm = (sigma_x_min_idx + 0.5) * dz_cm if sigma_x_min_idx >= 0 else float("nan")
    z_hat_sigma_y_min_cm = (sigma_y_min_idx + 0.5) * dz_cm if sigma_y_min_idx >= 0 else float("nan")

    entrance_on_axis_pct = float("nan")
    exit_on_axis_pct = float("nan")
    if peak_on_axis > 0:
        entrance_on_axis_pct = 100.0 * float(on_axis[0]) / peak_on_axis
        exit_on_axis_pct = 100.0 * float(on_axis[-1]) / peak_on_axis

    entrance_plane_max_pct = float("nan")
    exit_plane_max_pct = float("nan")
    if global_peak > 0:
        entrance_plane_max_pct = 100.0 * float(np.max(grid[:, :, 0])) / global_peak
        exit_plane_max_pct = 100.0 * float(np.max(grid[:, :, nz - 1])) / global_peak

    entrance_integrated_pct = float("nan")
    exit_integrated_pct = float("nan")
    if peak_integrated > 0:
        entrance_integrated_pct = 100.0 * float(depth_integrated[0]) / peak_integrated
        exit_integrated_pct = 100.0 * float(depth_integrated[nz - 1]) / peak_integrated

    return {
        "z_hat_cm": z_hat_integrated_cm,
        "z_hat_on_axis_cm": z_hat_on_axis_cm,
        "z_hat_integrated_cm": z_hat_integrated_cm,
        "z_hat_global_cm": z_hat_global_cm,
        "sigma_x_cm": sigma_x_integrated_cm,
        "sigma_y_cm": sigma_y_integrated_cm,
        "sigma_x_integrated_cm": sigma_x_integrated_cm,
        "sigma_y_integrated_cm": sigma_y_integrated_cm,
        "sigma_x_on_axis_cm": sigma_x_on_axis_cm,
        "sigma_y_on_axis_cm": sigma_y_on_axis_cm,
        "sigma_x_global_cm": sigma_x_global_cm,
        "sigma_y_global_cm": sigma_y_global_cm,
        "sigma_x_independent_min_cm": sigma_x_independent_min_cm,
        "sigma_y_independent_min_cm": sigma_y_independent_min_cm,
        "z_hat_sigma_x_min_cm": z_hat_sigma_x_min_cm,
        "z_hat_sigma_y_min_cm": z_hat_sigma_y_min_cm,
        "sigma_fit_mode_used": sigma_fit_mode,
        "sigma_x_integrated_profile_cm": sigma_x_integrated_profile_cm,
        "sigma_y_integrated_profile_cm": sigma_y_integrated_profile_cm,
        "sigma_x_on_axis_profile_cm": sigma_x_on_axis_profile_cm,
        "sigma_y_on_axis_profile_cm": sigma_y_on_axis_profile_cm,
        "sigma_x_on_axis_center_profile_cm": sigma_x_on_axis_center_profile_cm,
        "sigma_y_on_axis_center_profile_cm": sigma_y_on_axis_center_profile_cm,
        "sigma_x_global_profile_cm": sigma_x_global_profile_cm,
        "sigma_y_global_profile_cm": sigma_y_global_profile_cm,
        "sigma_x_integrated_2d_cm": sigma_x_integrated_2d_cm,
        "sigma_y_integrated_2d_cm": sigma_y_integrated_2d_cm,
        "sigma_x_on_axis_2d_cm": sigma_x_on_axis_2d_cm,
        "sigma_y_on_axis_2d_cm": sigma_y_on_axis_2d_cm,
        "sigma_x_global_2d_cm": sigma_x_global_2d_cm,
        "sigma_y_global_2d_cm": sigma_y_global_2d_cm,
        "sigma_x_entrance_2d_cm": sigma_x_entrance_2d_cm,
        "sigma_y_entrance_2d_cm": sigma_y_entrance_2d_cm,
        "sigma_x_weighted_integrated_cm": sigma_x_weighted_integrated_cm,
        "sigma_y_weighted_integrated_cm": sigma_y_weighted_integrated_cm,
        "sigma_x_weighted_cm": sigma_x_weighted_cm,
        "sigma_y_weighted_cm": sigma_y_weighted_cm,
        "sigma_x_weighted_on_axis_cm": sigma_x_weighted_cm,
        "sigma_y_weighted_on_axis_cm": sigma_y_weighted_cm,
        "sigma_x_weighted_global_cm": sigma_x_weighted_global_cm,
        "sigma_y_weighted_global_cm": sigma_y_weighted_global_cm,
        "paper_strict_mode_used": bool(sigma_fit_mode == "paper_strict"),
        "entrance_on_axis_pct": entrance_on_axis_pct,
        "exit_on_axis_pct": exit_on_axis_pct,
        "entrance_plane_max_pct": entrance_plane_max_pct,
        "exit_plane_max_pct": exit_plane_max_pct,
        "entrance_integrated_pct": entrance_integrated_pct,
        "exit_integrated_pct": exit_integrated_pct,
        "peak_index_z": peak_index_integrated,
        "peak_index_z_on_axis": peak_index_on_axis,
        "peak_index_z_integrated": peak_index_integrated,
        "peak_index_z_global": int(peak_index_global_z),
        "peak_index_sigma_x_min": int(sigma_x_min_idx),
        "peak_index_sigma_y_min": int(sigma_y_min_idx),
        "peak_index_x_integrated": int(ix_peak_integrated),
        "peak_index_y_integrated": int(iy_peak_integrated),
        "peak_index_x": int(ix_peak),
        "peak_index_y": int(iy_peak),
        "peak_index_x_global": int(peak_index_global_x),
        "peak_index_y_global": int(peak_index_global_y),
        "peak_integrated_dose": peak_integrated,
        "peak_on_axis_dose": peak_on_axis,
        "peak_global_dose": global_peak,
        "nx": int(nx),
        "ny": int(ny),
        "nz": int(nz),
        "dx_cm": float(dx_cm),
        "dy_cm": float(dy_cm),
        "dz_cm": float(dz_cm),
    }


def find_table3_row(reference: Dict, energy_mev: int, g4_tpm: float) -> Optional[Dict]:
    entry = reference["asymmetric_beamline"]["energies"].get(str(energy_mev))
    if not entry:
        return None
    for row in entry["supplementary_table3_scan"]:
        if abs(float(row["g4_t_per_m"]) - g4_tpm) < 1e-9:
            return row
    return None


def benchmark_for_energy(reference: Dict, energy_mev: int) -> Optional[Dict]:
    entry = reference["asymmetric_beamline"]["energies"].get(str(energy_mev))
    if not entry:
        return None
    return entry["benchmark_metrics_table2"]


def score_against_benchmark(
    metrics: Dict[str, float],
    benchmark: Dict[str, float],
    entrance_mode: str,
    tol_z_cm: float,
    tol_sx_cm: float,
    tol_sy_cm: float,
    tol_ent_pct: float,
    z_mode: str = "on_axis",
    sigma_mode: str = "on_axis",
) -> Dict[str, float]:
    if entrance_mode == "on_axis":
        entrance_value = metrics["entrance_on_axis_pct"]
    elif entrance_mode == "integrated_xy":
        entrance_value = metrics["entrance_integrated_pct"]
    else:
        entrance_value = metrics["entrance_plane_max_pct"]

    z_value = (
        float(metrics["z_hat_integrated_cm"])
        if z_mode == "integrated_xy"
        else (
            float(metrics["z_hat_global_cm"])
            if z_mode == "global_max"
            else float(metrics["z_hat_on_axis_cm"])
        )
    )
    sigma_x_value = (
        float(metrics["sigma_x_integrated_cm"])
        if sigma_mode == "integrated_xy"
        else (
            float(metrics["sigma_x_global_cm"])
            if sigma_mode == "global_max"
            else (
                float(metrics["sigma_x_independent_min_cm"])
                if sigma_mode == "independent_xy_min"
                else float(metrics["sigma_x_on_axis_cm"])
            )
        )
    )
    sigma_y_value = (
        float(metrics["sigma_y_integrated_cm"])
        if sigma_mode == "integrated_xy"
        else (
            float(metrics["sigma_y_global_cm"])
            if sigma_mode == "global_max"
            else (
                float(metrics["sigma_y_independent_min_cm"])
                if sigma_mode == "independent_xy_min"
                else float(metrics["sigma_y_on_axis_cm"])
            )
        )
    )
    if sigma_mode == "independent_xy_min":
        sigma_x_depth_value = float(metrics["z_hat_sigma_x_min_cm"])
        sigma_y_depth_value = float(metrics["z_hat_sigma_y_min_cm"])
    elif sigma_mode == "on_axis":
        sigma_x_depth_value = float(metrics["z_hat_on_axis_cm"])
        sigma_y_depth_value = float(metrics["z_hat_on_axis_cm"])
    elif sigma_mode == "global_max":
        sigma_x_depth_value = float(metrics["z_hat_global_cm"])
        sigma_y_depth_value = float(metrics["z_hat_global_cm"])
    else:
        sigma_x_depth_value = float(metrics["z_hat_integrated_cm"])
        sigma_y_depth_value = float(metrics["z_hat_integrated_cm"])
    dz = z_value - float(benchmark["z_hat_cm"])
    dsx = sigma_x_value - float(benchmark["sigma_x_cm"])
    dsy = sigma_y_value - float(benchmark["sigma_y_cm"])
    dent = entrance_value - float(benchmark["entrance_dose_pct"])

    terms = [
        (dz / tol_z_cm) ** 2,
        (dsx / tol_sx_cm) ** 2,
        (dsy / tol_sy_cm) ** 2,
        (dent / tol_ent_pct) ** 2,
    ]
    weighted_error = math.sqrt(sum(terms))

    within = (
        abs(dz) <= tol_z_cm
        and abs(dsx) <= tol_sx_cm
        and abs(dsy) <= tol_sy_cm
        and abs(dent) <= tol_ent_pct
    )
    return {
        "delta_z_hat_cm": dz,
        "delta_sigma_x_cm": dsx,
        "delta_sigma_y_cm": dsy,
        "delta_entrance_pct": dent,
        "entrance_mode_used": entrance_mode,
        "entrance_selected_pct": float(entrance_value),
        "weighted_error": weighted_error,
        "within_tolerance": bool(within),
        "z_mode_used": z_mode,
        "z_hat_selected_cm": z_value,
        "sigma_mode_used": sigma_mode,
        "sigma_x_selected_cm": sigma_x_value,
        "sigma_y_selected_cm": sigma_y_value,
        "sigma_x_selected_depth_cm": sigma_x_depth_value,
        "sigma_y_selected_depth_cm": sigma_y_depth_value,
    }


def analyze_case(
    csv_path: Path,
    reference: Dict,
    energy_mev: Optional[int],
    g4_tpm: Optional[float],
    args: argparse.Namespace,
    case_id: str = "",
) -> Dict[str, object]:
    grid, header = load_topas_grid(
        csv_path,
        retries=args.io_retries,
        retry_delay_sec=args.io_retry_delay_sec,
    )
    metrics = extract_metrics_from_grid(
        grid,
        dx_cm=float(header["dx_cm"]),
        dy_cm=float(header["dy_cm"]),
        dz_cm=float(header["dz_cm"]),
        sigma_fit_mode=args.sigma_fit_mode,
    )

    row: Dict[str, object] = {
        "case_id": case_id if case_id else csv_path.stem,
        "csv_file": str(csv_path.resolve()),
        "energy_mev": energy_mev,
        "g4_t_per_m": g4_tpm,
        **metrics,
    }

    if energy_mev is not None:
        benchmark = benchmark_for_energy(reference, energy_mev)
        if benchmark is not None:
            scored = score_against_benchmark(
                metrics=metrics,
                benchmark=benchmark,
                entrance_mode=args.entrance_mode,
                tol_z_cm=args.tol_z_cm,
                tol_sx_cm=args.tol_sigma_x_cm,
                tol_sy_cm=args.tol_sigma_y_cm,
                tol_ent_pct=args.tol_entrance_pct,
                z_mode=args.z_mode,
                sigma_mode=args.sigma_mode,
            )
            row.update(scored)
            row["benchmark_sigma_x_cm"] = float(benchmark["sigma_x_cm"])
            row["benchmark_sigma_y_cm"] = float(benchmark["sigma_y_cm"])
            row["benchmark_z_hat_cm"] = float(benchmark["z_hat_cm"])
            row["benchmark_entrance_pct"] = float(benchmark["entrance_dose_pct"])
            row["delta_z_hat_on_axis_cm"] = float(metrics["z_hat_on_axis_cm"]) - float(
                benchmark["z_hat_cm"]
            )
            row["delta_z_hat_integrated_cm"] = float(metrics["z_hat_integrated_cm"]) - float(
                benchmark["z_hat_cm"]
            )
            row["delta_z_hat_global_cm"] = float(metrics["z_hat_global_cm"]) - float(
                benchmark["z_hat_cm"]
            )
            row["delta_sigma_x_integrated_cm"] = float(metrics["sigma_x_integrated_cm"]) - float(
                benchmark["sigma_x_cm"]
            )
            row["delta_sigma_x_on_axis_cm"] = float(metrics["sigma_x_on_axis_cm"]) - float(
                benchmark["sigma_x_cm"]
            )
            row["delta_sigma_x_global_cm"] = float(metrics["sigma_x_global_cm"]) - float(
                benchmark["sigma_x_cm"]
            )
            row["delta_sigma_x_independent_cm"] = float(
                metrics["sigma_x_independent_min_cm"]
            ) - float(benchmark["sigma_x_cm"])
            row["delta_sigma_y_integrated_cm"] = float(metrics["sigma_y_integrated_cm"]) - float(
                benchmark["sigma_y_cm"]
            )
            row["delta_sigma_y_on_axis_cm"] = float(metrics["sigma_y_on_axis_cm"]) - float(
                benchmark["sigma_y_cm"]
            )
            row["delta_sigma_y_global_cm"] = float(metrics["sigma_y_global_cm"]) - float(
                benchmark["sigma_y_cm"]
            )
            row["delta_sigma_y_independent_cm"] = float(
                metrics["sigma_y_independent_min_cm"]
            ) - float(benchmark["sigma_y_cm"])

            scored_integrated = score_against_benchmark(
                metrics=metrics,
                benchmark=benchmark,
                entrance_mode=args.entrance_mode,
                tol_z_cm=args.tol_z_cm,
                tol_sx_cm=args.tol_sigma_x_cm,
                tol_sy_cm=args.tol_sigma_y_cm,
                tol_ent_pct=args.tol_entrance_pct,
                z_mode="integrated_xy",
                sigma_mode="integrated_xy",
            )
            row["weighted_error_integrated"] = float(scored_integrated["weighted_error"])
            row["within_tolerance_integrated"] = bool(scored_integrated["within_tolerance"])

            scored_on_axis = score_against_benchmark(
                metrics=metrics,
                benchmark=benchmark,
                entrance_mode=args.entrance_mode,
                tol_z_cm=args.tol_z_cm,
                tol_sx_cm=args.tol_sigma_x_cm,
                tol_sy_cm=args.tol_sigma_y_cm,
                tol_ent_pct=args.tol_entrance_pct,
                z_mode="on_axis",
                sigma_mode="on_axis",
            )
            scored_global = score_against_benchmark(
                metrics=metrics,
                benchmark=benchmark,
                entrance_mode=args.entrance_mode,
                tol_z_cm=args.tol_z_cm,
                tol_sx_cm=args.tol_sigma_x_cm,
                tol_sy_cm=args.tol_sigma_y_cm,
                tol_ent_pct=args.tol_entrance_pct,
                z_mode="global_max",
                sigma_mode="global_max",
            )
            row["weighted_error_on_axis"] = float(scored_on_axis["weighted_error"])
            row["within_tolerance_on_axis"] = bool(scored_on_axis["within_tolerance"])
            row["weighted_error_global"] = float(scored_global["weighted_error"])
            row["within_tolerance_global"] = bool(scored_global["within_tolerance"])
            scored_independent = score_against_benchmark(
                metrics=metrics,
                benchmark=benchmark,
                entrance_mode=args.entrance_mode,
                tol_z_cm=args.tol_z_cm,
                tol_sx_cm=args.tol_sigma_x_cm,
                tol_sy_cm=args.tol_sigma_y_cm,
                tol_ent_pct=args.tol_entrance_pct,
                z_mode=args.z_mode,
                sigma_mode="independent_xy_min",
            )
            row["weighted_error_sigma_independent"] = float(
                scored_independent["weighted_error"]
            )
            row["within_tolerance_sigma_independent"] = bool(
                scored_independent["within_tolerance"]
            )
            scored_z_global_sigma_on_axis = score_against_benchmark(
                metrics=metrics,
                benchmark=benchmark,
                entrance_mode=args.entrance_mode,
                tol_z_cm=args.tol_z_cm,
                tol_sx_cm=args.tol_sigma_x_cm,
                tol_sy_cm=args.tol_sigma_y_cm,
                tol_ent_pct=args.tol_entrance_pct,
                z_mode="global_max",
                sigma_mode="on_axis",
            )
            scored_z_on_axis_sigma_global = score_against_benchmark(
                metrics=metrics,
                benchmark=benchmark,
                entrance_mode=args.entrance_mode,
                tol_z_cm=args.tol_z_cm,
                tol_sx_cm=args.tol_sigma_x_cm,
                tol_sy_cm=args.tol_sigma_y_cm,
                tol_ent_pct=args.tol_entrance_pct,
                z_mode="on_axis",
                sigma_mode="global_max",
            )
            row["weighted_error_z_global_sigma_on_axis"] = float(
                scored_z_global_sigma_on_axis["weighted_error"]
            )
            row["weighted_error_z_on_axis_sigma_global"] = float(
                scored_z_on_axis_sigma_global["weighted_error"]
            )

        if g4_tpm is not None and not math.isnan(g4_tpm):
            ref_scan_row = find_table3_row(reference, energy_mev, g4_tpm)
            if ref_scan_row is not None:
                row["ref_table3_z_hat_cm"] = float(ref_scan_row["z_hat_cm"])
                row["delta_z_hat_vs_table3_cm"] = (
                    float(metrics["z_hat_cm"]) - float(ref_scan_row["z_hat_cm"])
                )
            else:
                row["ref_table3_z_hat_cm"] = float("nan")
                row["delta_z_hat_vs_table3_cm"] = float("nan")

    return row


def write_validation_report(
    out_file: Path, best_df: pd.DataFrame, args: argparse.Namespace, total_cases: int
) -> None:
    lines = []
    lines.append("# Focused beamline Validation Report")
    lines.append("")
    lines.append(f"- Generated (UTC): {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    lines.append(f"- Cases analyzed: {total_cases}")
    lines.append(f"- Entrance metric mode: `{args.entrance_mode}`")
    lines.append(f"- z-hat mode for scoring: `{args.z_mode}`")
    lines.append(f"- Sigma mode for scoring: `{args.sigma_mode}`")
    lines.append(f"- Sigma fit mode: `{args.sigma_fit_mode}`")
    if getattr(args, "paper_strict", False):
        lines.append(
            "- Paper-strict override active: `z_mode=on_axis`, `sigma_mode=on_axis`, "
            "`entrance_mode=on_axis`, `sigma_fit_mode=paper_strict`."
        )
    lines.append(
        "- Tolerances: "
        f"z={args.tol_z_cm:.3f} cm, "
        f"sigma_x={args.tol_sigma_x_cm:.3f} cm, "
        f"sigma_y={args.tol_sigma_y_cm:.3f} cm, "
        f"entrance={args.tol_entrance_pct:.3f}%"
    )
    lines.append("")

    if best_df.empty:
        lines.append("No valid TOPAS CSV files were available for analysis.")
    else:
        lines.append("| Energy (MeV) | Best Case | g4 (T/m) | z_hat_sel (cm) | z_hat_int (cm) | z_hat_on_axis (cm) | z_hat_global (cm) | sigma_x_sel (cm) | z(sigma_x_sel) (cm) | sigma_x_int (cm) | sigma_x_on_axis (cm) | sigma_x_global (cm) | sigma_y_sel (cm) | z(sigma_y_sel) (cm) | sigma_y_int (cm) | sigma_y_on_axis (cm) | sigma_y_global (cm) | Entrance (%) | Weighted Error | Within Tol |")
        lines.append("|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|")
        for _, row in best_df.sort_values("energy_mev").iterrows():
            if args.entrance_mode == "on_axis":
                entrance = row["entrance_on_axis_pct"]
            elif args.entrance_mode == "integrated_xy":
                entrance = row["entrance_integrated_pct"]
            else:
                entrance = row["entrance_plane_max_pct"]
            lines.append(
                "| "
                f"{int(row['energy_mev'])} | "
                f"{row['case_id']} | "
                f"{row['g4_t_per_m']:.4f} | "
                f"{row['z_hat_selected_cm']:.3f} | "
                f"{row['z_hat_integrated_cm']:.3f} | "
                f"{row['z_hat_on_axis_cm']:.3f} | "
                f"{row['z_hat_global_cm']:.3f} | "
                f"{row['sigma_x_selected_cm']:.3f} | "
                f"{row['sigma_x_selected_depth_cm']:.3f} | "
                f"{row['sigma_x_integrated_cm']:.3f} | "
                f"{row['sigma_x_on_axis_cm']:.3f} | "
                f"{row['sigma_x_global_cm']:.3f} | "
                f"{row['sigma_y_selected_cm']:.3f} | "
                f"{row['sigma_y_selected_depth_cm']:.3f} | "
                f"{row['sigma_y_integrated_cm']:.3f} | "
                f"{row['sigma_y_on_axis_cm']:.3f} | "
                f"{row['sigma_y_global_cm']:.3f} | "
                f"{entrance:.2f} | "
                f"{row['weighted_error']:.3f} | "
                f"{'PASS' if bool(row['within_tolerance']) else 'FAIL'} |"
            )

    out_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def manifest_mode(args: argparse.Namespace, reference: Dict) -> int:
    if not args.manifest.exists():
        raise FileNotFoundError(f"Manifest not found: {args.manifest}")
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    cases = manifest.get("cases", [])
    if not cases:
        raise ValueError(f"No cases found in manifest: {args.manifest}")

    rows: List[Dict[str, object]] = []
    missing: List[str] = []
    unreadable: List[Tuple[str, str]] = []
    for case in cases:
        csv_path = Path(case["dose_csv"])
        if not csv_path.exists():
            missing.append(case["case_id"])
            continue
        gradients = case.get("gradients_t_per_m", [])
        if not gradients:
            gradients = case.get("paper_gradients_t_per_m", [])
        if not gradients:
            gradients = case.get("gradient_x_t_per_m", [])
        g4_tpm = float(gradients[3]) if len(gradients) >= 4 else float("nan")
        try:
            rows.append(
                analyze_case(
                    csv_path=csv_path,
                    reference=reference,
                    energy_mev=int(case["energy_mev"]),
                    g4_tpm=g4_tpm,
                    args=args,
                    case_id=case["case_id"],
                )
            )
        except Exception as exc:
            unreadable.append((case["case_id"], f"{type(exc).__name__}: {exc}"))
            continue

    outdir = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)
    if not rows:
        print("No existing CSV files were found for analysis.")
        print(f"Missing outputs for {len(missing)} case(s).")
        if unreadable:
            print(f"Unreadable CSV files for {len(unreadable)} case(s).")
        return 1

    df = pd.DataFrame(rows)
    df = df.sort_values(["energy_mev", "g4_t_per_m", "case_id"], na_position="last")
    case_metrics_file = outdir / "case_metrics.csv"
    df.to_csv(case_metrics_file, index=False)

    best_rows = []
    for energy, group in df.groupby("energy_mev"):
        valid = group.dropna(subset=["weighted_error"])
        if valid.empty:
            continue
        best_rows.append(valid.loc[valid["weighted_error"].idxmin()])
    best_df = pd.DataFrame(best_rows) if best_rows else pd.DataFrame()

    best_file = outdir / "best_per_energy.csv"
    best_df.to_csv(best_file, index=False)

    report_file = outdir / "validation_report.md"
    write_validation_report(report_file, best_df, args, total_cases=len(df))

    print(f"Case metrics: {case_metrics_file}")
    print(f"Best per energy: {best_file}")
    print(f"Validation report: {report_file}")
    if missing:
        print(f"Skipped (missing CSV): {len(missing)} case(s)")
    if unreadable:
        print(f"Skipped (unreadable CSV): {len(unreadable)} case(s)")
        for case_id, reason in unreadable[:10]:
            print(f"  {case_id}: {reason}")

    if not best_df.empty:
        for _, row in best_df.sort_values("energy_mev").iterrows():
            state = "PASS" if bool(row.get("within_tolerance", False)) else "FAIL"
            print(
                f"E={int(row['energy_mev'])} MeV | best={row['case_id']} | "
                f"g4={row['g4_t_per_m']:.4f} T/m | error={row['weighted_error']:.3f} | {state}"
            )
    return 0


def direct_csv_mode(args: argparse.Namespace, reference: Dict) -> int:
    if not args.csv:
        return 1
    energy = args.energy if args.energy > 0 else None
    g4 = None
    if not math.isnan(args.g4):
        g4 = float(args.g4)

    rows = []
    for csv_path in args.csv:
        if not csv_path.exists():
            print(f"Missing CSV: {csv_path}")
            continue
        try:
            rows.append(
                analyze_case(
                    csv_path=csv_path,
                    reference=reference,
                    energy_mev=energy,
                    g4_tpm=g4,
                    args=args,
                )
            )
        except Exception as exc:
            print(f"Unreadable CSV: {csv_path} ({type(exc).__name__}: {exc})")
            continue
    if not rows:
        return 1

    df = pd.DataFrame(rows)
    display_cols = [
        "case_id",
        "energy_mev",
        "g4_t_per_m",
        "sigma_fit_mode_used",
        "z_hat_integrated_cm",
        "z_hat_on_axis_cm",
        "z_hat_global_cm",
        "z_hat_selected_cm",
        "sigma_x_integrated_cm",
        "sigma_x_on_axis_cm",
        "sigma_x_global_cm",
        "sigma_x_independent_min_cm",
        "z_hat_sigma_x_min_cm",
        "sigma_x_selected_cm",
        "sigma_x_selected_depth_cm",
        "sigma_y_integrated_cm",
        "sigma_y_on_axis_cm",
        "sigma_y_global_cm",
        "sigma_y_independent_min_cm",
        "z_hat_sigma_y_min_cm",
        "sigma_y_selected_cm",
        "sigma_y_selected_depth_cm",
        "sigma_x_entrance_2d_cm",
        "sigma_y_entrance_2d_cm",
        "entrance_integrated_pct",
        "entrance_on_axis_pct",
        "entrance_plane_max_pct",
        "exit_integrated_pct",
        "exit_on_axis_pct",
        "exit_plane_max_pct",
    ]
    extra_cols = [c for c in ("weighted_error", "within_tolerance") if c in df.columns]
    print(df[display_cols + extra_cols].to_string(index=False))
    return 0


def main() -> int:
    args = parse_args()
    reference = load_reference(args.reference)
    if args.csv:
        return direct_csv_mode(args, reference)
    return manifest_mode(args, reference)


if __name__ == "__main__":
    raise SystemExit(main())
